#!/bin/zsh

export ZSH=${ZSH:-$HOME/.oh-my-zsh}

ZSH_THEME="mmarchini"

# TODO(mmarchini): OS and env specific plugins
plugins=(
  docker
  git
  macos
  multipass
  node
  npm
  nvm
  virtualenv
  zsh-autosuggestions
  zsh-syntax-highlighting
)

set +e
source $ZSH/oh-my-zsh.sh
set -e
