#!/bin/zsh

export ZSH=${ZSH:-$HOME/.oh-my-zsh}

ZSH_THEME="mmarchini"

zstyle ':omz:plugins:nvm' lazy yes

# TODO(mmarchini): OS and env specific plugins
plugins=(
  nvm
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
