#!/bin/zsh

source "$DOTFILES_PATH/helpers/path"
source "$DOTFILES_PATH/helpers/source"

# Python global binaries
PYTHON2_VERSION=$(python2 --version 2>&1 | awk '{ print $2 }' | cut -d'.' -f1,2)
PYTHON3_VERSION=$(python3 --version 2>&1 | awk '{ print $2 }' | cut -d'.' -f1,2)
prependPathIfExists "$HOME/.local/bin"
prependPathIfExists "$HOME/.poetry/bin"

# Go global binaries
export GOPATH=$HOME/go/gopath
prependPathIfExists "$GOPATH"
prependPathIfExists "$HOME/go/bin"

# cargo (Rust global binaries)
sourceIfExists $HOME/.cargo/env

# gem (Ruby)
export GEM_HOME="$HOME/.gem"
