#!/bin/zsh

git-root() { cd $(git rev-parse --show-toplevel) }

nodejs() { cd $HOME/workspace/nodejs/$1 }

coredump () { ulimit -c unlimited; $@; ulimit -c 0 }

zshprofiling () {
  ZSH_PROFILING=1 /usr/bin/time zsh -i -c exit
}

alias duh='du -sh .[!.]* *'
alias vim="vim -p"
alias xim="xargs -o vim -p"
alias c="code -r"
alias docker-rm-exited='docker rm -v $(docker ps -a -q -f status=exited)'
