#!/usr/bin/env python3

import re
import sys

# TODO(mmarchini) investigate using `html.parser.HTMLParser` instead of regex
html = sys.stdin.readlines()
html = "".join(html)
html = re.sub(r"<!--((?:.|\s|\n)*?)-->", "", html)
print(html)
