#!/bin/bash

set -e;

GPG_IS_CACHED=$(~/.bin/gpg-status);

if test "$GPG_IS_CACHED" != "gtg"; then
  echo "GPG not authenticated. Skipping..." >> ~/.mutt/log/cron.mbsync.log;
  exit 1;
fi

echo "Running" >> ~/.mutt/log/cron.mbsync.log;

# Sync e-mails
# TODO(mmarchini) get accounts from config or from accounts folder
/usr/local/bin/mbsync -V mmarchini                     2>> ~/.mutt/log/mbsync.mmarchini.log >> ~/.mutt/log/mbsync.mmarchini.log

date +%s > ~/.mutt/.last-sync

# Update notmut index
/usr/local/bin/notmuch new                             2>> ~/.mutt/log/notmuch.log >> ~/.mutt/log/notmuch.log;

# Apply notmuch tags
/usr/bin/python ~/.mutt/scripts/tag-mailboxes          2>> ~/.mutt/log/notmuch.log >> ~/.mutt/log/notmuch.log;
