# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!


general {
  colors = true
  color_good = "#d0d150"
  color_degraded = "#e99d2a"
  color_bad = "#be2d26"
  color_separator = "#573d26"
  interval = 5
}

order += "spotify"
order += "volume_status"
order += "disk /"
order += "sysdata"
order += "wifi"
order += "ethernet eth0"
order += 'backlight'
order += "battery 0"
order += "tztime local"
order += "static_string power_off"

backlight {
  hide_when_unavailable = True
}

static_string power_off {
  format = " O "
  color = "#573d26"
  on_click 1 = "exec i3-exit"
}

spotify {
  button_next = 3
  button_play_pause = 1
  color_playing = "#559F51"
  color_paused = "#d0d150"
  color_offline = "#559F51"
}

sysdata {
    format = "M {mem_used_percent}% C {cpu_usage}%"
    high_threshold = 80
    med_threshold = 65
}

wifi {
  format = "W: {signal_percent}% {ssid}|W: down"
  format_up = ""
  format_down = ""
}

ethernet eth0 {
  # if you use %speed, i3status requires root privileges
  format_up = "N %ip"
  format_down = ""
}

battery 0 {
  hide_seconds = true
  integer_battery_capacity = true
  status_bat = "B"
  status_chr = "C"
  status_full = "F"
  format = "%status %percentage %remaining"
}

tztime local {
  format = "%d/%m/%Y %H:%M"
}

disk "/" {
  format = "D %avail"
}
