######################
### DESIGN CHANGES ###
######################

## Status bar design
# status line
# set -g status-utf8 on
set -g status-justify centre
set -g status-interval 2

# messaging
set -g message-command-fg blue
set -g message-command-bg black

#
set -g pane-base-index 1
set -g base-index 1

# I'm too fast :(
set -sg escape-time 25

# loud or quiet?
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-window-option -g monitor-activity off
set-option -g bell-action none

set -g default-terminal "screen-256color"

# The modes {
setw -g clock-mode-colour colour135
setw -g mode-attr bold
setw -g mode-fg colour196
setw -g mode-bg colour238

# }
# The panes {

set -g pane-border-bg colour0
set -g pane-border-fg colour8
set -g pane-active-border-bg colour0
set -g pane-active-border-fg colour11

# }
# The statusbar {

set -g status-position bottom
set -g status-bg default
set -g status-fg colour7
set -g status-attr dim
# status-left is set dynamically via crontab
set -g status-left ' '
# set -g status-left '#[bg=colour8,fg=colour7] Last sync #(email-last-sync) ago #[bg=colour2,fg=colour8]#[bg=colour3,fg=colour0] GPG: #(gpg-status) #[fg=colour3,bg=default] '
# set -g status-right '#[fg=colour233,bg=colour241,bold] %d/%m #[fg=colour233,bg=colour245,bold] %H:%M:%S '
set -g status-right '#[fg=colour11,bg=default]#[bg=colour11,fg=colour0] %d/%m %H:%M #[fg=colour8,bg=colour11]#[bg=colour8,fg=colour7] #{battery_remain} [#{battery_percentage}] '
set -g status-right-length 50
set -g status-left-length 50

setw -g window-status-current-fg colour7
setw -g window-status-current-bg colour12
setw -g window-status-current-attr bold
setw -g window-status-current-format ' #I:#W#[fg=1]#F '

setw -g window-status-fg colour7
setw -g window-status-bg colour0
setw -g window-status-attr none
setw -g window-status-format ' #I:#W#[fg=2]#F '

setw -g window-status-bell-attr bold
setw -g window-status-bell-fg colour255
setw -g window-status-bell-bg colour1

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set-option -g default-shell /usr/bin/zsh

# }
# The messages {

set -g message-attr bold
set -g message-fg colour15
set -g message-bg colour5

# }

# Mouse options {
set -g mouse on
# }

# Battery {
# set -g @batt_charged_icon "😎"
# set -g @batt_charging_icon "👍"
# set -g @batt_attached_icon "😐"
# set -g @batt_full_charge_icon "🌕 "
# set -g @batt_high_charge_icon "🌖 "
# set -g @batt_medium_charge_icon "🌗 "
# set -g @batt_low_charge_icon "🌘 "
set -g @batt_remain_short true
# }

# Plugins {
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-battery'

run '~/.tmux/plugins/tpm/tpm'
# }
