#!/bin/zsh

if [ ! -z "$ZSH_PROFILING" ]; then
  zmodload zsh/zprof
fi

# Ensure we don't have `set -e`, `set -e` bad
set +e

# TODO(mmarchini): deduplicate
export DOTFILES_PATH="$(dirname $(dirname ${${(%):-%N}:A}))"

for file in "${DOTFILES_PATH}/zsh/source"/*; do
  source "$file"
done

zsh "$DOTFILES_PATH/helpers/sync-dotfiles"

if [ ! -z "$ZSH_PROFILING" ]; then
  zprof
fi
