#!/bin/zsh

# Ensure we don't have `set -e`, `set -e` bad
set +e

if [ ! -z "$ZSH_PROFILING" ]; then
  START=$(($(date +%s%N)/1000000))
  zmodload zsh/zprof
fi
#
# TODO(mmarchini): deduplicate
export DOTFILES_PATH="$(dirname $(dirname ${${(%):-%N}:A}))"


source "$DOTFILES_PATH/helpers/source"
source "$DOTFILES_PATH/bin/binrc"

for file in "${DOTFILES_PATH}/zsh/source"/*; do
  source "$file"
done

sourceIfExists "${HOME}/.localzshrc"

if [ ! -z "$ZSH_PROFILING" ]; then
  zprof
  echo "Ran in $(($(date +%s%N)/1000000 - "$START")) milliseconds";
fi

#TODO: add motd
