#!/bin/zsh

ZSH_THEME="mmarchini"

# TODO(mmarchini): OS and env specific plugins
plugins=(
  git
  docker
  npm
  osx
  virtualenv
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
