#cloud-config
users:
  - default
  - name: mmarchini
    gecos: Mary Marchini
    primary_group: mmarchini
    shell: /bin/zsh
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    # ssh_import_id: None
    lock_passwd: true
    ssh_authorized_keys:
      - ${id_rsa_pub_content}

write_files:
  - content: |
${id_rsa_content}
    path: /home/mmarchini/.ssh/id_rsa
    owner: mmarchini:mmarchini
    defer: true
    permissions: '0600'
  - content: |
      ${id_rsa_pub_content}
    path: /home/mmarchini/.ssh/id_rsa.pub
    owner: mmarchini:mmarchini
    defer: true
    permissions: '0600'

package_update: true
package_upgrade: true
packages:
  - zsh
  - curl
runcmd:
  - curl -sf -L https://raw.githubusercontent.com/mmarchini/dotfiles/main/install.sh | sudo -u mmarchini zsh
